function varargout = roiViewerGUI(varargin)
% ROIVIEWERGUI MATLAB code for roiViewerGUI.fig
%      ROIVIEWERGUI, by itself, creates a new ROIVIEWERGUI or raises the existing
%      singleton*.
%
%      H = ROIVIEWERGUI returns the handle to a new ROIVIEWERGUI or the handle to
%      the existing singleton*.
%
%      ROIVIEWERGUI('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in ROIVIEWERGUI.M with the given input arguments.
%
%      ROIVIEWERGUI('Property','Value',...) creates a new ROIVIEWERGUI or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before roiViewerGUI_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to roiViewerGUI_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help roiViewerGUI

% Last Modified by GUIDE v2.5 11-Jun-2019 11:23:47

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @roiViewerGUI_OpeningFcn, ...
                   'gui_OutputFcn',  @roiViewerGUI_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT

% --- Executes just before roiViewerGUI is made visible.
function roiViewerGUI_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% varargin   command line arguments to roiViewerGUI (see VARARGIN)

global gui

gui.axes.h1 = handles.axes1;
gui.axes.h2 = handles.axes2;
gui.axes.h3 = handles.axes3;

% init variables for filter values
gui.filters.enableSNR = 0;
gui.filters.enablenumStates = 0;
gui.filters.snr_min = [];
gui.filters.snr_max = [];
gui.filters.numstates_min = [];
gui.filters.numstates_max = [];

% Choose default command line output for roiViewerGUI
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% This sets up the initial plot - only do when we are invisible
% so window can get raised using roiViewerGUI.
% initial load of ROI 1 at channel 1
if strcmp(get(hObject,'Visible'),'off')
    gui.channelIdx = 1;
    goToROI(1);
end


% --- Outputs from this function are returned to the command line.
function varargout = roiViewerGUI_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);

% Get default command line output from handles structure
varargout{1} = handles.output;

% --------------------------------------------------------------------
function OpenMenuItem_Callback(hObject, eventdata, handles)
% autogenerated and unused, as the file menu calls the custom loadData function
file = uigetfile('*.fig');
if ~isequal(file, 0)
    open(file);
end

% --------------------------------------------------------------------
function PrintMenuItem_Callback(hObject, eventdata, handles)
% loads the standard print dialog
printdlg(handles.figure1)

% --------------------------------------------------------------------
function CloseMenuItem_Callback(hObject, eventdata, handles)
% autogenerated and unused, as there is no necessary "close" option in the file menu
selection = questdlg(['Close ' get(handles.figure1,'Name') '?'],...
                     ['Close ' get(handles.figure1,'Name') '...'],...
                     'Yes','No','Yes');
if strcmp(selection,'No')
    return
end

delete(handles.figure1)


% --- Executes on selection change in popupmenu_channelSelect.
function popupmenu_channelSelect_Callback(hObject, eventdata, handles)
% changes the channel selected via popup, and remains on the current ROI.
% Supports an arbitrary number of channels
global data gui 

popup_sel_index = get(handles.popupmenu_channelSelect, 'Value');
for ii = 1:size(data.rois,2)
    switch popup_sel_index
        case ii
            gui.channelIdx = ii;
            goToROI(gui.roiIdx);
    end
end


% --- Executes during object creation, after setting all properties.
function popupmenu_channelSelect_CreateFcn(hObject, eventdata, handles)
% creates popup and fetches channel names
% Supports an arbitrary number of channels (though colors would need to be
% adapted as such in initChannels)
global data
% create menu with default colors
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
     set(hObject,'BackgroundColor','white');
end

% set popup values based on channel names
set(hObject, 'String', data.names);
set(hObject, 'Value', 1);
set(hObject, 'fontsize', 12);
set(hObject, 'fontname', 'SansSerif');


% --- Executes on button press in pushbutton_nextROI.
function pushbutton_nextROI_Callback(hObject, eventdata, handles)
% go to the next ROI, stops at end of channel
global gui
goToROI(gui.roiIdx + 1);


% --- Executes on button press in pushbutton_prevROI.
function pushbutton_prevROI_Callback(hObject, eventdata, handles)
% go to the previous ROI, stops at 1
global gui
goToROI(gui.roiIdx - 1);


% --- Executes on button press in pushbutton_customROI.
function pushbutton_customROI_Callback(hObject, eventdata, handles)
% jump to any given ROI via a dialog
goToROI();


% --- Executes on button press in pushbutton_analyzeThis.
function pushbutton_analyzeThis_Callback(hObject, eventdata, handles)
% sets condition to run DISC on the current ROI and brings up param dialog
analyzeDialog(0);


% --- Executes on button press in pushbutton_analyzeAll.
function pushbutton_analyzeAll_Callback(hObject, eventdata, handles)
% sets condition to run DISC on all ROIs and brings up param dialog
analyzeDialog(1);


% --- Executes on key press with focus on figure1 or any of its controls.
function figure1_WindowKeyPressFcn(hObject, eventdata, handles)
% handles all key presses as labeled on buttons. easily extended with the
% proper strings
switch eventdata.Key
    case 'rightarrow'
        uicontrol(handles.pushbutton_nextROI)
        pushbutton_nextROI_Callback(handles.pushbutton_nextROI,[],handles)
    case 'leftarrow'
        uicontrol(handles.pushbutton_prevROI)
        pushbutton_prevROI_Callback(handles.pushbutton_prevROI,[],handles)
    case 'uparrow'
        uicontrol(handles.pushbutton_toggleSelect)
        pushbutton_toggleSelect_Callback(handles.pushbutton_toggleSelect,[],handles)
    case 'downarrow'
        uicontrol(handles.pushbutton_toggleDeselect)
        pushbutton_toggleDeselect_Callback(handles.pushbutton_toggleDeselect,[],handles)
    case 'period'
        uicontrol(handles.pushbutton_nextSelected)
        pushbutton_nextSelected_Callback(handles.pushbutton_nextSelected,[],handles)
    case 'comma'
        uicontrol(handles.pushbutton_prevSelected)
        pushbutton_prevSelected_Callback(handles.pushbutton_prevSelected,[],handles)
end


% --- Executes on button press in pushbutton_clearThis.
function pushbutton_clearThis_Callback(hObject, eventdata, handles)
% clears analysis fields for current ROI
global data gui
data.rois(gui.roiIdx,gui.channelIdx).disc_fit = [];
data.rois(gui.roiIdx,gui.channelIdx).SNR = [];
goToROI(gui.roiIdx)

% --- Executes on button press in pushbutton_clearAll.
function pushbutton_clearAll_Callback(hObject, eventdata, handles)
% clears analysis fields for all ROIs
global data gui
[data.rois(:,gui.channelIdx).disc_fit] = deal([]);
[data.rois(:,gui.channelIdx).SNR] = deal([]);
goToROI(gui.roiIdx)


% --- Executes on button press in pushbutton_toggleSelect.
function pushbutton_toggleSelect_Callback(hObject, eventdata, handles)
% change "status" field for ROI and title if necessary
global data gui
% change status on all channels
for ii = 1:size(data.rois,2)
    data.rois(gui.roiIdx,ii).status = 1;
end
ax1 = handles.axes1;
% count # of selected
numsel = nnz(vertcat(data.rois(:,gui.channelIdx).status)==1);
if data.rois(gui.roiIdx,gui.channelIdx).status == 1
    title(ax1, ['ROI # ',num2str(gui.roiIdx),' of ',num2str(size(data.rois,1)),...
        ' - Status: Selected','  (',num2str(numsel),' selected)']);
elseif data.rois(gui.roiIdx,gui.channelIdx).status == 0
    title(ax1, ['ROI # ',num2str(gui.roiIdx),' of ',num2str(size(data.rois,1)),...
        ' - Status: Unselected','  (',num2str(numsel),' selected)']);
else
    title(ax1, ['ROI # ',num2str(gui.roiIdx),' of ',num2str(size(data.rois,1)),...
        ' - Status: null','  (',num2str(numsel),' selected)']);
end

% --- Executes on button press in pushbutton_toggleDeselect.
function pushbutton_toggleDeselect_Callback(hObject, eventdata, handles)
% change "status" field for ROI and title if necessary
global data gui
% change status on all channels
for ii = 1:size(data.rois, 2)
    data.rois(gui.roiIdx,ii).status = 0;
end
ax1 = handles.axes1;
% count # of selected
numsel = nnz(vertcat(data.rois(:,gui.channelIdx).status)==1);
if data.rois(gui.roiIdx,gui.channelIdx).status == 1
    title(ax1, ['ROI # ',num2str(gui.roiIdx),' of ',num2str(size(data.rois,1)),...
        ' - Status: Selected','  (',num2str(numsel),' selected)']);
elseif data.rois(gui.roiIdx,gui.channelIdx).status == 0
    title(ax1, ['ROI # ',num2str(gui.roiIdx),' of ',num2str(size(data.rois,1)),...
        ' - Status: Unselected','  (',num2str(numsel),' selected)']);
else
    title(ax1, ['ROI # ',num2str(gui.roiIdx),' of ',num2str(size(data.rois,1)),...
        ' - Status: null','  (',num2str(numsel),' selected)']);
end

% --- Executes on button press in pushbutton_nextSelected.
function pushbutton_nextSelected_Callback(hObject, eventdata, handles)
% finds next ROI with "selected" status and goes to it in the GUI
global data gui  
    j = find(vertcat(data.rois(gui.roiIdx+1:end,gui.channelIdx).status) == 1);
    if ~isempty(j) 
        goToROI(gui.roiIdx + j(1)); 
    end

% --- Executes on button press in pushbutton_prevSelected.
function pushbutton_prevSelected_Callback(hObject, eventdata, handles)
% finds previous ROI with "selected" status and goes to it in the GUI
global data gui
    j = find(vertcat(data.rois(1:gui.roiIdx-1,gui.channelIdx).status) == 1);
    if ~isempty(j) 
        goToROI(j(end)); 
    end

    
% --- Executes on button press in pushbutton_filter.
function pushbutton_filter_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_filter (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global data gui

traceSelection();
% cancel if continue is not pressed
if ~gui.filters.contpr
    handles.text_snr_filt.String = 'any';
    handles.text_numstates_filt.String = 'any';
    return;
end
% if cancel is pressed, no filter will be applied, but the traces from the
% previous filtering will still be selected.

% assign min and max values if entry boxes are left empty
if gui.filters.enableSNR && isempty(gui.filters.snr_max)
    gui.filters.snr_max = Inf;
end
if gui.filters.enableSNR && isempty(gui.filters.snr_min)
    gui.filters.snr_min = -Inf;
end
if gui.filters.enablenumStates && isempty(gui.filters.numstates_max)
    gui.filters.numstates_max = Inf;
end
if gui.filters.enablenumStates && isempty(gui.filters.numstates_min)
    gui.filters.numstates_min = 0;
end

[data.rois.status] = deal(0); % clear any existing selections

% sort by SNR only
if gui.filters.snrEnable && ~gui.filters.numstatesEnable
    % change corresponding text in GUI
    handles.text_snr_filt.String = [num2str(gui.filters.snr_min),...
        ' → ', num2str(gui.filters.snr_max)];
    handles.text_numstates_filt.String = 'any';
    computeSNR(0); % fill field in data struct
    % adjust trace status if parameters are met
    for ii = 1:size(data.rois, 1)
        if ~isempty(data.rois(ii,gui.channelIdx).SNR)
            trace_snr = data.rois(ii,gui.channelIdx).SNR;
            if trace_snr <= gui.filters.snr_max && ...
                    trace_snr >= gui.filters.snr_min
                for jj = 1:size(data.rois,2)
                    data.rois(ii,jj).status = 1;
                end
            end
        end
    end
% sort by # of states only
elseif gui.filters.numstatesEnable && ~gui.filters.snrEnable
    % change corresponding text in GUI
    handles.text_numstates_filt.String = [num2str(gui.filters.numstates_min),...
        ' → ', num2str(gui.filters.numstates_max)];
    handles.text_snr_filt.String = 'any';
    % adjust trace status if parameters are met
    for ii = 1:size(data.rois, 1)
        if ~isempty(data.rois(ii,gui.channelIdx).disc_fit)
            n_components = size(data.rois(ii,gui.channelIdx).disc_fit.components,1);
            if n_components <= gui.filters.numstates_max && ...
                    n_components >= gui.filters.numstates_min
                for jj = 1:size(data.rois,2)
                    data.rois(ii,jj).status = 1;
                end
            end
        end
    end
% sort by SNR and # of states
elseif gui.filters.numstatesEnable && gui.filters.snrEnable
    % change corresponding text in GUI
    handles.text_snr_filt.String = [num2str(gui.filters.snr_min),...
        ' → ', num2str(gui.filters.snr_max)];
    computeSNR(0);
    handles.text_numstates_filt.String = [num2str(gui.filters.numstates_min),...
        ' → ', num2str(gui.filters.numstates_max)];
    % adjust trace status if parameters are met
    for ii = 1:size(data.rois, 1)
        if ~isempty(data.rois(ii,gui.channelIdx).disc_fit)
            n_components = size(data.rois(ii,gui.channelIdx).disc_fit.components,1);
            trace_snr = data.rois(ii,gui.channelIdx).SNR;
            if n_components <= gui.filters.numstates_max && ...
                    n_components >= gui.filters.numstates_min && ...
                    trace_snr <= gui.filters.snr_max && ...
                    trace_snr >= gui.filters.snr_min
                for jj = 1:size(data.rois,2)
                    data.rois(ii,jj).status = 1;
                end
            end
        end
    end
end
% redraw titles
goToROI(gui.roiIdx);

% unused
function menuFile_Callback(~, ~, ~)
function menuPlots_Callback(~, ~, ~)
